### PR TITLE
Remove old widget code and replace with ToggleButton using sdk/ui

### PR DESCRIPTION
**Pull request by zacc**
This pull request adds an intermediate panel with menu options for choosing to scrape with an existing script or to edit/create a new script. As the left click/right click menu options no longer work with the ToggleButton, this needed to be added.

The icon is changed to a static icon but uses the badge to represent how many scripts are available on that page and show that the page can be scraped. The icon is also disabled on non-http tabs.

I tried to avoid any unnecessary changes to the code and tried to follow the prevailing style.

However if you're unhappy with some parts of this code, feel free to take the commit and modify it yourself before merging!

Cheers

### CODE REVIEW

**Comment by zacc** [comment]
@izderadicka can you comment on this PR? Are you considering merging it at all?

**Comment by izderadicka** [comment]
Hi Zacc,
thanks for contribution,   surely I'm considering merge,   just did not have time to look at it.
I.

**Comment by izderadicka** [comment]
Merged with few additional small changes to make it compatible with jpm - thanks a lot

**Comment by zacc** [comment]
:+1: !

**Pull request merged**
